package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TAddressPrep extends TAddressPrepKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.rep_name
     *
     * @mbg.generated
     */
    private String repName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.block_count
     *
     * @mbg.generated
     */
    private Integer blockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.is_prep
     *
     * @mbg.generated
     */
    private Boolean isPrep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.start_term
     *
     * @mbg.generated
     */
    private Integer startTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.end_term
     *
     * @mbg.generated
     */
    private Integer endTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.rep_hash
     *
     * @mbg.generated
     */
    private String repHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_PREP.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.rep_name
     *
     * @return the value of T_ADDRESS_PREP.rep_name
     *
     * @mbg.generated
     */
    public String getRepName() {
        return repName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.rep_name
     *
     * @param repName the value for T_ADDRESS_PREP.rep_name
     *
     * @mbg.generated
     */
    public void setRepName(String repName) {
        this.repName = repName == null ? null : repName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.block_count
     *
     * @return the value of T_ADDRESS_PREP.block_count
     *
     * @mbg.generated
     */
    public Integer getBlockCount() {
        return blockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.block_count
     *
     * @param blockCount the value for T_ADDRESS_PREP.block_count
     *
     * @mbg.generated
     */
    public void setBlockCount(Integer blockCount) {
        this.blockCount = blockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.is_prep
     *
     * @return the value of T_ADDRESS_PREP.is_prep
     *
     * @mbg.generated
     */
    public Boolean getIsPrep() {
        return isPrep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.is_prep
     *
     * @param isPrep the value for T_ADDRESS_PREP.is_prep
     *
     * @mbg.generated
     */
    public void setIsPrep(Boolean isPrep) {
        this.isPrep = isPrep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.start_term
     *
     * @return the value of T_ADDRESS_PREP.start_term
     *
     * @mbg.generated
     */
    public Integer getStartTerm() {
        return startTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.start_term
     *
     * @param startTerm the value for T_ADDRESS_PREP.start_term
     *
     * @mbg.generated
     */
    public void setStartTerm(Integer startTerm) {
        this.startTerm = startTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.end_term
     *
     * @return the value of T_ADDRESS_PREP.end_term
     *
     * @mbg.generated
     */
    public Integer getEndTerm() {
        return endTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.end_term
     *
     * @param endTerm the value for T_ADDRESS_PREP.end_term
     *
     * @mbg.generated
     */
    public void setEndTerm(Integer endTerm) {
        this.endTerm = endTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.url
     *
     * @return the value of T_ADDRESS_PREP.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.url
     *
     * @param url the value for T_ADDRESS_PREP.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.rep_hash
     *
     * @return the value of T_ADDRESS_PREP.rep_hash
     *
     * @mbg.generated
     */
    public String getRepHash() {
        return repHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.rep_hash
     *
     * @param repHash the value for T_ADDRESS_PREP.rep_hash
     *
     * @mbg.generated
     */
    public void setRepHash(String repHash) {
        this.repHash = repHash == null ? null : repHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_PREP.update_date
     *
     * @return the value of T_ADDRESS_PREP.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_PREP.update_date
     *
     * @param updateDate the value for T_ADDRESS_PREP.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}