package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TAddressReport extends TAddressReportKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_REPORT.reported_addr
     *
     * @mbg.generated
     */
    private String reportedAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_REPORT.reporter_addr
     *
     * @mbg.generated
     */
    private String reporterAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_REPORT.report_type
     *
     * @mbg.generated
     */
    private Byte reportType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_REPORT.image_file
     *
     * @mbg.generated
     */
    private String imageFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_REPORT.ref_url
     *
     * @mbg.generated
     */
    private String refUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADDRESS_REPORT.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_REPORT.reported_addr
     *
     * @return the value of T_ADDRESS_REPORT.reported_addr
     *
     * @mbg.generated
     */
    public String getReportedAddr() {
        return reportedAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_REPORT.reported_addr
     *
     * @param reportedAddr the value for T_ADDRESS_REPORT.reported_addr
     *
     * @mbg.generated
     */
    public void setReportedAddr(String reportedAddr) {
        this.reportedAddr = reportedAddr == null ? null : reportedAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_REPORT.reporter_addr
     *
     * @return the value of T_ADDRESS_REPORT.reporter_addr
     *
     * @mbg.generated
     */
    public String getReporterAddr() {
        return reporterAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_REPORT.reporter_addr
     *
     * @param reporterAddr the value for T_ADDRESS_REPORT.reporter_addr
     *
     * @mbg.generated
     */
    public void setReporterAddr(String reporterAddr) {
        this.reporterAddr = reporterAddr == null ? null : reporterAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_REPORT.report_type
     *
     * @return the value of T_ADDRESS_REPORT.report_type
     *
     * @mbg.generated
     */
    public Byte getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_REPORT.report_type
     *
     * @param reportType the value for T_ADDRESS_REPORT.report_type
     *
     * @mbg.generated
     */
    public void setReportType(Byte reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_REPORT.image_file
     *
     * @return the value of T_ADDRESS_REPORT.image_file
     *
     * @mbg.generated
     */
    public String getImageFile() {
        return imageFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_REPORT.image_file
     *
     * @param imageFile the value for T_ADDRESS_REPORT.image_file
     *
     * @mbg.generated
     */
    public void setImageFile(String imageFile) {
        this.imageFile = imageFile == null ? null : imageFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_REPORT.ref_url
     *
     * @return the value of T_ADDRESS_REPORT.ref_url
     *
     * @mbg.generated
     */
    public String getRefUrl() {
        return refUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_REPORT.ref_url
     *
     * @param refUrl the value for T_ADDRESS_REPORT.ref_url
     *
     * @mbg.generated
     */
    public void setRefUrl(String refUrl) {
        this.refUrl = refUrl == null ? null : refUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADDRESS_REPORT.create_date
     *
     * @return the value of T_ADDRESS_REPORT.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADDRESS_REPORT.create_date
     *
     * @param createDate the value for T_ADDRESS_REPORT.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}