package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TBlockTotal extends TBlockTotalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.tx_count
     *
     * @mbg.generated
     */
    private Integer txCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.prev_hash
     *
     * @mbg.generated
     */
    private String prevHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.block_size
     *
     * @mbg.generated
     */
    private Integer blockSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.fee
     *
     * @mbg.generated
     */
    private String fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.hash
     *
     * @return the value of T_BLOCK_TOTAL.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.hash
     *
     * @param hash the value for T_BLOCK_TOTAL.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.height
     *
     * @return the value of T_BLOCK_TOTAL.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.height
     *
     * @param height the value for T_BLOCK_TOTAL.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.create_date
     *
     * @return the value of T_BLOCK_TOTAL.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.create_date
     *
     * @param createDate the value for T_BLOCK_TOTAL.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.tx_count
     *
     * @return the value of T_BLOCK_TOTAL.tx_count
     *
     * @mbg.generated
     */
    public Integer getTxCount() {
        return txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.tx_count
     *
     * @param txCount the value for T_BLOCK_TOTAL.tx_count
     *
     * @mbg.generated
     */
    public void setTxCount(Integer txCount) {
        this.txCount = txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.prev_hash
     *
     * @return the value of T_BLOCK_TOTAL.prev_hash
     *
     * @mbg.generated
     */
    public String getPrevHash() {
        return prevHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.prev_hash
     *
     * @param prevHash the value for T_BLOCK_TOTAL.prev_hash
     *
     * @mbg.generated
     */
    public void setPrevHash(String prevHash) {
        this.prevHash = prevHash == null ? null : prevHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.block_size
     *
     * @return the value of T_BLOCK_TOTAL.block_size
     *
     * @mbg.generated
     */
    public Integer getBlockSize() {
        return blockSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.block_size
     *
     * @param blockSize the value for T_BLOCK_TOTAL.block_size
     *
     * @mbg.generated
     */
    public void setBlockSize(Integer blockSize) {
        this.blockSize = blockSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.fee
     *
     * @return the value of T_BLOCK_TOTAL.fee
     *
     * @mbg.generated
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.fee
     *
     * @param fee the value for T_BLOCK_TOTAL.fee
     *
     * @mbg.generated
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.amount
     *
     * @return the value of T_BLOCK_TOTAL.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.amount
     *
     * @param amount the value for T_BLOCK_TOTAL.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }
}