package com.dfg.icon.core.dao.icon;

public class TBlockKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK.height
     *
     * @return the value of T_BLOCK.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK.height
     *
     * @param height the value for T_BLOCK.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }
}