package com.dfg.icon.core.dao.icon;

public class TBlockTotalKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_TOTAL.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_TOTAL.id
     *
     * @return the value of T_BLOCK_TOTAL.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_TOTAL.id
     *
     * @param id the value for T_BLOCK_TOTAL.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}