package com.dfg.icon.core.dao.icon;

public class TBtpHeaderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.block_height
     *
     * @mbg.generated
     */
    private Integer blockHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.network_id
     *
     * @mbg.generated
     */
    private String networkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.block_height
     *
     * @return the value of T_BTP_HEADER.block_height
     *
     * @mbg.generated
     */
    public Integer getBlockHeight() {
        return blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.block_height
     *
     * @param blockHeight the value for T_BTP_HEADER.block_height
     *
     * @mbg.generated
     */
    public void setBlockHeight(Integer blockHeight) {
        this.blockHeight = blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.network_id
     *
     * @return the value of T_BTP_HEADER.network_id
     *
     * @mbg.generated
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.network_id
     *
     * @param networkId the value for T_BTP_HEADER.network_id
     *
     * @mbg.generated
     */
    public void setNetworkId(String networkId) {
        this.networkId = networkId == null ? null : networkId.trim();
    }
}