package com.dfg.icon.core.dao.icon;

import java.util.ArrayList;
import java.util.List;

public class TBtpNetworkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public TBtpNetworkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNetworkIdIsNull() {
            addCriterion("network_id is null");
            return (Criteria) this;
        }

        public Criteria andNetworkIdIsNotNull() {
            addCriterion("network_id is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkIdEqualTo(String value) {
            addCriterion("network_id =", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdNotEqualTo(String value) {
            addCriterion("network_id <>", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdGreaterThan(String value) {
            addCriterion("network_id >", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdGreaterThanOrEqualTo(String value) {
            addCriterion("network_id >=", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdLessThan(String value) {
            addCriterion("network_id <", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdLessThanOrEqualTo(String value) {
            addCriterion("network_id <=", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdLike(String value) {
            addCriterion("network_id like", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdNotLike(String value) {
            addCriterion("network_id not like", value, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdIn(List<String> values) {
            addCriterion("network_id in", values, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdNotIn(List<String> values) {
            addCriterion("network_id not in", values, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdBetween(String value1, String value2) {
            addCriterion("network_id between", value1, value2, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkIdNotBetween(String value1, String value2) {
            addCriterion("network_id not between", value1, value2, "networkId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdIsNull() {
            addCriterion("network_type_id is null");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdIsNotNull() {
            addCriterion("network_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdEqualTo(String value) {
            addCriterion("network_type_id =", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdNotEqualTo(String value) {
            addCriterion("network_type_id <>", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdGreaterThan(String value) {
            addCriterion("network_type_id >", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("network_type_id >=", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdLessThan(String value) {
            addCriterion("network_type_id <", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdLessThanOrEqualTo(String value) {
            addCriterion("network_type_id <=", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdLike(String value) {
            addCriterion("network_type_id like", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdNotLike(String value) {
            addCriterion("network_type_id not like", value, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdIn(List<String> values) {
            addCriterion("network_type_id in", values, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdNotIn(List<String> values) {
            addCriterion("network_type_id not in", values, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdBetween(String value1, String value2) {
            addCriterion("network_type_id between", value1, value2, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeIdNotBetween(String value1, String value2) {
            addCriterion("network_type_id not between", value1, value2, "networkTypeId");
            return (Criteria) this;
        }

        public Criteria andNetworkNameIsNull() {
            addCriterion("network_name is null");
            return (Criteria) this;
        }

        public Criteria andNetworkNameIsNotNull() {
            addCriterion("network_name is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkNameEqualTo(String value) {
            addCriterion("network_name =", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameNotEqualTo(String value) {
            addCriterion("network_name <>", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameGreaterThan(String value) {
            addCriterion("network_name >", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameGreaterThanOrEqualTo(String value) {
            addCriterion("network_name >=", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameLessThan(String value) {
            addCriterion("network_name <", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameLessThanOrEqualTo(String value) {
            addCriterion("network_name <=", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameLike(String value) {
            addCriterion("network_name like", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameNotLike(String value) {
            addCriterion("network_name not like", value, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameIn(List<String> values) {
            addCriterion("network_name in", values, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameNotIn(List<String> values) {
            addCriterion("network_name not in", values, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameBetween(String value1, String value2) {
            addCriterion("network_name between", value1, value2, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkNameNotBetween(String value1, String value2) {
            addCriterion("network_name not between", value1, value2, "networkName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameIsNull() {
            addCriterion("network_type_name is null");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameIsNotNull() {
            addCriterion("network_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameEqualTo(String value) {
            addCriterion("network_type_name =", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameNotEqualTo(String value) {
            addCriterion("network_type_name <>", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameGreaterThan(String value) {
            addCriterion("network_type_name >", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("network_type_name >=", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameLessThan(String value) {
            addCriterion("network_type_name <", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameLessThanOrEqualTo(String value) {
            addCriterion("network_type_name <=", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameLike(String value) {
            addCriterion("network_type_name like", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameNotLike(String value) {
            addCriterion("network_type_name not like", value, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameIn(List<String> values) {
            addCriterion("network_type_name in", values, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameNotIn(List<String> values) {
            addCriterion("network_type_name not in", values, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameBetween(String value1, String value2) {
            addCriterion("network_type_name between", value1, value2, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andNetworkTypeNameNotBetween(String value1, String value2) {
            addCriterion("network_type_name not between", value1, value2, "networkTypeName");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andStartHeightIsNull() {
            addCriterion("start_height is null");
            return (Criteria) this;
        }

        public Criteria andStartHeightIsNotNull() {
            addCriterion("start_height is not null");
            return (Criteria) this;
        }

        public Criteria andStartHeightEqualTo(Integer value) {
            addCriterion("start_height =", value, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightNotEqualTo(Integer value) {
            addCriterion("start_height <>", value, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightGreaterThan(Integer value) {
            addCriterion("start_height >", value, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("start_height >=", value, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightLessThan(Integer value) {
            addCriterion("start_height <", value, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightLessThanOrEqualTo(Integer value) {
            addCriterion("start_height <=", value, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightIn(List<Integer> values) {
            addCriterion("start_height in", values, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightNotIn(List<Integer> values) {
            addCriterion("start_height not in", values, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightBetween(Integer value1, Integer value2) {
            addCriterion("start_height between", value1, value2, "startHeight");
            return (Criteria) this;
        }

        public Criteria andStartHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("start_height not between", value1, value2, "startHeight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}