package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TBtpHeader extends TBtpHeaderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.update_number
     *
     * @mbg.generated
     */
    private String updateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.prev
     *
     * @mbg.generated
     */
    private String prev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.message_cnt
     *
     * @mbg.generated
     */
    private Integer messageCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.message_root
     *
     * @mbg.generated
     */
    private String messageRoot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BTP_HEADER.btp_network_network_id
     *
     * @mbg.generated
     */
    private String btpNetworkNetworkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.update_number
     *
     * @return the value of T_BTP_HEADER.update_number
     *
     * @mbg.generated
     */
    public String getUpdateNumber() {
        return updateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.update_number
     *
     * @param updateNumber the value for T_BTP_HEADER.update_number
     *
     * @mbg.generated
     */
    public void setUpdateNumber(String updateNumber) {
        this.updateNumber = updateNumber == null ? null : updateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.prev
     *
     * @return the value of T_BTP_HEADER.prev
     *
     * @mbg.generated
     */
    public String getPrev() {
        return prev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.prev
     *
     * @param prev the value for T_BTP_HEADER.prev
     *
     * @mbg.generated
     */
    public void setPrev(String prev) {
        this.prev = prev == null ? null : prev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.message_cnt
     *
     * @return the value of T_BTP_HEADER.message_cnt
     *
     * @mbg.generated
     */
    public Integer getMessageCnt() {
        return messageCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.message_cnt
     *
     * @param messageCnt the value for T_BTP_HEADER.message_cnt
     *
     * @mbg.generated
     */
    public void setMessageCnt(Integer messageCnt) {
        this.messageCnt = messageCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.message_root
     *
     * @return the value of T_BTP_HEADER.message_root
     *
     * @mbg.generated
     */
    public String getMessageRoot() {
        return messageRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.message_root
     *
     * @param messageRoot the value for T_BTP_HEADER.message_root
     *
     * @mbg.generated
     */
    public void setMessageRoot(String messageRoot) {
        this.messageRoot = messageRoot == null ? null : messageRoot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.create_date
     *
     * @return the value of T_BTP_HEADER.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.create_date
     *
     * @param createDate the value for T_BTP_HEADER.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BTP_HEADER.btp_network_network_id
     *
     * @return the value of T_BTP_HEADER.btp_network_network_id
     *
     * @mbg.generated
     */
    public String getBtpNetworkNetworkId() {
        return btpNetworkNetworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BTP_HEADER.btp_network_network_id
     *
     * @param btpNetworkNetworkId the value for T_BTP_HEADER.btp_network_network_id
     *
     * @mbg.generated
     */
    public void setBtpNetworkNetworkId(String btpNetworkNetworkId) {
        this.btpNetworkNetworkId = btpNetworkNetworkId == null ? null : btpNetworkNetworkId.trim();
    }
}