package com.dfg.icon.core.dao.icon;

public class TChainState extends TChainStateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CHAIN_STATE.block_height
     *
     * @mbg.generated
     */
    private Integer blockHeight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CHAIN_STATE.block_height
     *
     * @return the value of T_CHAIN_STATE.block_height
     *
     * @mbg.generated
     */
    public Integer getBlockHeight() {
        return blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CHAIN_STATE.block_height
     *
     * @param blockHeight the value for T_CHAIN_STATE.block_height
     *
     * @mbg.generated
     */
    public void setBlockHeight(Integer blockHeight) {
        this.blockHeight = blockHeight;
    }
}