package com.dfg.icon.core.dao.icon;

public class TChainInfo extends TChainInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CHAIN_INFO.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CHAIN_INFO.api
     *
     * @mbg.generated
     */
    private String api;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CHAIN_INFO.channel
     *
     * @mbg.generated
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CHAIN_INFO.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CHAIN_INFO.host
     *
     * @return the value of T_CHAIN_INFO.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CHAIN_INFO.host
     *
     * @param host the value for T_CHAIN_INFO.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CHAIN_INFO.api
     *
     * @return the value of T_CHAIN_INFO.api
     *
     * @mbg.generated
     */
    public String getApi() {
        return api;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CHAIN_INFO.api
     *
     * @param api the value for T_CHAIN_INFO.api
     *
     * @mbg.generated
     */
    public void setApi(String api) {
        this.api = api == null ? null : api.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CHAIN_INFO.channel
     *
     * @return the value of T_CHAIN_INFO.channel
     *
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CHAIN_INFO.channel
     *
     * @param channel the value for T_CHAIN_INFO.channel
     *
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CHAIN_INFO.version
     *
     * @return the value of T_CHAIN_INFO.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CHAIN_INFO.version
     *
     * @param version the value for T_CHAIN_INFO.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}