package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TContractHistory extends TContractHistoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.compiler
     *
     * @mbg.generated
     */
    private String compiler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.create_tx
     *
     * @mbg.generated
     */
    private String createTx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.verified_tx
     *
     * @mbg.generated
     */
    private String verifiedTx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.verified_date
     *
     * @mbg.generated
     */
    private Date verifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.compiler
     *
     * @return the value of T_CONTRACT_HISTORY.compiler
     *
     * @mbg.generated
     */
    public String getCompiler() {
        return compiler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.compiler
     *
     * @param compiler the value for T_CONTRACT_HISTORY.compiler
     *
     * @mbg.generated
     */
    public void setCompiler(String compiler) {
        this.compiler = compiler == null ? null : compiler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.create_tx
     *
     * @return the value of T_CONTRACT_HISTORY.create_tx
     *
     * @mbg.generated
     */
    public String getCreateTx() {
        return createTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.create_tx
     *
     * @param createTx the value for T_CONTRACT_HISTORY.create_tx
     *
     * @mbg.generated
     */
    public void setCreateTx(String createTx) {
        this.createTx = createTx == null ? null : createTx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.create_date
     *
     * @return the value of T_CONTRACT_HISTORY.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.create_date
     *
     * @param createDate the value for T_CONTRACT_HISTORY.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.verified_tx
     *
     * @return the value of T_CONTRACT_HISTORY.verified_tx
     *
     * @mbg.generated
     */
    public String getVerifiedTx() {
        return verifiedTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.verified_tx
     *
     * @param verifiedTx the value for T_CONTRACT_HISTORY.verified_tx
     *
     * @mbg.generated
     */
    public void setVerifiedTx(String verifiedTx) {
        this.verifiedTx = verifiedTx == null ? null : verifiedTx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.verified_date
     *
     * @return the value of T_CONTRACT_HISTORY.verified_date
     *
     * @mbg.generated
     */
    public Date getVerifiedDate() {
        return verifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.verified_date
     *
     * @param verifiedDate the value for T_CONTRACT_HISTORY.verified_date
     *
     * @mbg.generated
     */
    public void setVerifiedDate(Date verifiedDate) {
        this.verifiedDate = verifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.creator
     *
     * @return the value of T_CONTRACT_HISTORY.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.creator
     *
     * @param creator the value for T_CONTRACT_HISTORY.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.state
     *
     * @return the value of T_CONTRACT_HISTORY.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.state
     *
     * @param state the value for T_CONTRACT_HISTORY.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}