package com.dfg.icon.core.dao.icon;

public class TContractHistoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.contract_addr
     *
     * @mbg.generated
     */
    private String contractAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CONTRACT_HISTORY.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.contract_addr
     *
     * @return the value of T_CONTRACT_HISTORY.contract_addr
     *
     * @mbg.generated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.contract_addr
     *
     * @param contractAddr the value for T_CONTRACT_HISTORY.contract_addr
     *
     * @mbg.generated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr == null ? null : contractAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CONTRACT_HISTORY.version
     *
     * @return the value of T_CONTRACT_HISTORY.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CONTRACT_HISTORY.version
     *
     * @param version the value for T_CONTRACT_HISTORY.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}