package com.dfg.icon.core.dao.icon;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TContractHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public TContractHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContractAddrIsNull() {
            addCriterion("contract_addr is null");
            return (Criteria) this;
        }

        public Criteria andContractAddrIsNotNull() {
            addCriterion("contract_addr is not null");
            return (Criteria) this;
        }

        public Criteria andContractAddrEqualTo(String value) {
            addCriterion("contract_addr =", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotEqualTo(String value) {
            addCriterion("contract_addr <>", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrGreaterThan(String value) {
            addCriterion("contract_addr >", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrGreaterThanOrEqualTo(String value) {
            addCriterion("contract_addr >=", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLessThan(String value) {
            addCriterion("contract_addr <", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLessThanOrEqualTo(String value) {
            addCriterion("contract_addr <=", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLike(String value) {
            addCriterion("contract_addr like", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotLike(String value) {
            addCriterion("contract_addr not like", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrIn(List<String> values) {
            addCriterion("contract_addr in", values, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotIn(List<String> values) {
            addCriterion("contract_addr not in", values, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrBetween(String value1, String value2) {
            addCriterion("contract_addr between", value1, value2, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotBetween(String value1, String value2) {
            addCriterion("contract_addr not between", value1, value2, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCompilerIsNull() {
            addCriterion("compiler is null");
            return (Criteria) this;
        }

        public Criteria andCompilerIsNotNull() {
            addCriterion("compiler is not null");
            return (Criteria) this;
        }

        public Criteria andCompilerEqualTo(String value) {
            addCriterion("compiler =", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerNotEqualTo(String value) {
            addCriterion("compiler <>", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerGreaterThan(String value) {
            addCriterion("compiler >", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerGreaterThanOrEqualTo(String value) {
            addCriterion("compiler >=", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerLessThan(String value) {
            addCriterion("compiler <", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerLessThanOrEqualTo(String value) {
            addCriterion("compiler <=", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerLike(String value) {
            addCriterion("compiler like", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerNotLike(String value) {
            addCriterion("compiler not like", value, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerIn(List<String> values) {
            addCriterion("compiler in", values, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerNotIn(List<String> values) {
            addCriterion("compiler not in", values, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerBetween(String value1, String value2) {
            addCriterion("compiler between", value1, value2, "compiler");
            return (Criteria) this;
        }

        public Criteria andCompilerNotBetween(String value1, String value2) {
            addCriterion("compiler not between", value1, value2, "compiler");
            return (Criteria) this;
        }

        public Criteria andCreateTxIsNull() {
            addCriterion("create_tx is null");
            return (Criteria) this;
        }

        public Criteria andCreateTxIsNotNull() {
            addCriterion("create_tx is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTxEqualTo(String value) {
            addCriterion("create_tx =", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxNotEqualTo(String value) {
            addCriterion("create_tx <>", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxGreaterThan(String value) {
            addCriterion("create_tx >", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxGreaterThanOrEqualTo(String value) {
            addCriterion("create_tx >=", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxLessThan(String value) {
            addCriterion("create_tx <", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxLessThanOrEqualTo(String value) {
            addCriterion("create_tx <=", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxLike(String value) {
            addCriterion("create_tx like", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxNotLike(String value) {
            addCriterion("create_tx not like", value, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxIn(List<String> values) {
            addCriterion("create_tx in", values, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxNotIn(List<String> values) {
            addCriterion("create_tx not in", values, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxBetween(String value1, String value2) {
            addCriterion("create_tx between", value1, value2, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateTxNotBetween(String value1, String value2) {
            addCriterion("create_tx not between", value1, value2, "createTx");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxIsNull() {
            addCriterion("verified_tx is null");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxIsNotNull() {
            addCriterion("verified_tx is not null");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxEqualTo(String value) {
            addCriterion("verified_tx =", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxNotEqualTo(String value) {
            addCriterion("verified_tx <>", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxGreaterThan(String value) {
            addCriterion("verified_tx >", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxGreaterThanOrEqualTo(String value) {
            addCriterion("verified_tx >=", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxLessThan(String value) {
            addCriterion("verified_tx <", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxLessThanOrEqualTo(String value) {
            addCriterion("verified_tx <=", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxLike(String value) {
            addCriterion("verified_tx like", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxNotLike(String value) {
            addCriterion("verified_tx not like", value, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxIn(List<String> values) {
            addCriterion("verified_tx in", values, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxNotIn(List<String> values) {
            addCriterion("verified_tx not in", values, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxBetween(String value1, String value2) {
            addCriterion("verified_tx between", value1, value2, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedTxNotBetween(String value1, String value2) {
            addCriterion("verified_tx not between", value1, value2, "verifiedTx");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateIsNull() {
            addCriterion("verified_date is null");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateIsNotNull() {
            addCriterion("verified_date is not null");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateEqualTo(Date value) {
            addCriterion("verified_date =", value, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateNotEqualTo(Date value) {
            addCriterion("verified_date <>", value, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateGreaterThan(Date value) {
            addCriterion("verified_date >", value, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("verified_date >=", value, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateLessThan(Date value) {
            addCriterion("verified_date <", value, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("verified_date <=", value, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateIn(List<Date> values) {
            addCriterion("verified_date in", values, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateNotIn(List<Date> values) {
            addCriterion("verified_date not in", values, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateBetween(Date value1, Date value2) {
            addCriterion("verified_date between", value1, value2, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andVerifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("verified_date not between", value1, value2, "verifiedDate");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_CONTRACT_HISTORY
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}