package com.dfg.icon.core.dao.icon;

import java.util.ArrayList;
import java.util.List;

public class TContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public TContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContractAddrIsNull() {
            addCriterion("contract_addr is null");
            return (Criteria) this;
        }

        public Criteria andContractAddrIsNotNull() {
            addCriterion("contract_addr is not null");
            return (Criteria) this;
        }

        public Criteria andContractAddrEqualTo(String value) {
            addCriterion("contract_addr =", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotEqualTo(String value) {
            addCriterion("contract_addr <>", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrGreaterThan(String value) {
            addCriterion("contract_addr >", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrGreaterThanOrEqualTo(String value) {
            addCriterion("contract_addr >=", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLessThan(String value) {
            addCriterion("contract_addr <", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLessThanOrEqualTo(String value) {
            addCriterion("contract_addr <=", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLike(String value) {
            addCriterion("contract_addr like", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotLike(String value) {
            addCriterion("contract_addr not like", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrIn(List<String> values) {
            addCriterion("contract_addr in", values, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotIn(List<String> values) {
            addCriterion("contract_addr not in", values, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrBetween(String value1, String value2) {
            addCriterion("contract_addr between", value1, value2, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotBetween(String value1, String value2) {
            addCriterion("contract_addr not between", value1, value2, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIrcVersionIsNull() {
            addCriterion("irc_version is null");
            return (Criteria) this;
        }

        public Criteria andIrcVersionIsNotNull() {
            addCriterion("irc_version is not null");
            return (Criteria) this;
        }

        public Criteria andIrcVersionEqualTo(String value) {
            addCriterion("irc_version =", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionNotEqualTo(String value) {
            addCriterion("irc_version <>", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionGreaterThan(String value) {
            addCriterion("irc_version >", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionGreaterThanOrEqualTo(String value) {
            addCriterion("irc_version >=", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionLessThan(String value) {
            addCriterion("irc_version <", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionLessThanOrEqualTo(String value) {
            addCriterion("irc_version <=", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionLike(String value) {
            addCriterion("irc_version like", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionNotLike(String value) {
            addCriterion("irc_version not like", value, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionIn(List<String> values) {
            addCriterion("irc_version in", values, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionNotIn(List<String> values) {
            addCriterion("irc_version not in", values, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionBetween(String value1, String value2) {
            addCriterion("irc_version between", value1, value2, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andIrcVersionNotBetween(String value1, String value2) {
            addCriterion("irc_version not between", value1, value2, "ircVersion");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNull() {
            addCriterion("symbol is null");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNotNull() {
            addCriterion("symbol is not null");
            return (Criteria) this;
        }

        public Criteria andSymbolEqualTo(String value) {
            addCriterion("symbol =", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotEqualTo(String value) {
            addCriterion("symbol <>", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThan(String value) {
            addCriterion("symbol >", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("symbol >=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThan(String value) {
            addCriterion("symbol <", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThanOrEqualTo(String value) {
            addCriterion("symbol <=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLike(String value) {
            addCriterion("symbol like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotLike(String value) {
            addCriterion("symbol not like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolIn(List<String> values) {
            addCriterion("symbol in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotIn(List<String> values) {
            addCriterion("symbol not in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolBetween(String value1, String value2) {
            addCriterion("symbol between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotBetween(String value1, String value2) {
            addCriterion("symbol not between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andHolderAddrIsNull() {
            addCriterion("holder_addr is null");
            return (Criteria) this;
        }

        public Criteria andHolderAddrIsNotNull() {
            addCriterion("holder_addr is not null");
            return (Criteria) this;
        }

        public Criteria andHolderAddrEqualTo(String value) {
            addCriterion("holder_addr =", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrNotEqualTo(String value) {
            addCriterion("holder_addr <>", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrGreaterThan(String value) {
            addCriterion("holder_addr >", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrGreaterThanOrEqualTo(String value) {
            addCriterion("holder_addr >=", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrLessThan(String value) {
            addCriterion("holder_addr <", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrLessThanOrEqualTo(String value) {
            addCriterion("holder_addr <=", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrLike(String value) {
            addCriterion("holder_addr like", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrNotLike(String value) {
            addCriterion("holder_addr not like", value, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrIn(List<String> values) {
            addCriterion("holder_addr in", values, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrNotIn(List<String> values) {
            addCriterion("holder_addr not in", values, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrBetween(String value1, String value2) {
            addCriterion("holder_addr between", value1, value2, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderAddrNotBetween(String value1, String value2) {
            addCriterion("holder_addr not between", value1, value2, "holderAddr");
            return (Criteria) this;
        }

        public Criteria andHolderCountIsNull() {
            addCriterion("holder_count is null");
            return (Criteria) this;
        }

        public Criteria andHolderCountIsNotNull() {
            addCriterion("holder_count is not null");
            return (Criteria) this;
        }

        public Criteria andHolderCountEqualTo(Integer value) {
            addCriterion("holder_count =", value, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountNotEqualTo(Integer value) {
            addCriterion("holder_count <>", value, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountGreaterThan(Integer value) {
            addCriterion("holder_count >", value, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("holder_count >=", value, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountLessThan(Integer value) {
            addCriterion("holder_count <", value, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountLessThanOrEqualTo(Integer value) {
            addCriterion("holder_count <=", value, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountIn(List<Integer> values) {
            addCriterion("holder_count in", values, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountNotIn(List<Integer> values) {
            addCriterion("holder_count not in", values, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountBetween(Integer value1, Integer value2) {
            addCriterion("holder_count between", value1, value2, "holderCount");
            return (Criteria) this;
        }

        public Criteria andHolderCountNotBetween(Integer value1, Integer value2) {
            addCriterion("holder_count not between", value1, value2, "holderCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountIsNull() {
            addCriterion("transfer_count is null");
            return (Criteria) this;
        }

        public Criteria andTransferCountIsNotNull() {
            addCriterion("transfer_count is not null");
            return (Criteria) this;
        }

        public Criteria andTransferCountEqualTo(Integer value) {
            addCriterion("transfer_count =", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountNotEqualTo(Integer value) {
            addCriterion("transfer_count <>", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountGreaterThan(Integer value) {
            addCriterion("transfer_count >", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("transfer_count >=", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountLessThan(Integer value) {
            addCriterion("transfer_count <", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountLessThanOrEqualTo(Integer value) {
            addCriterion("transfer_count <=", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountIn(List<Integer> values) {
            addCriterion("transfer_count in", values, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountNotIn(List<Integer> values) {
            addCriterion("transfer_count not in", values, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountBetween(Integer value1, Integer value2) {
            addCriterion("transfer_count between", value1, value2, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountNotBetween(Integer value1, Integer value2) {
            addCriterion("transfer_count not between", value1, value2, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyIsNull() {
            addCriterion("total_supply is null");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyIsNotNull() {
            addCriterion("total_supply is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyEqualTo(String value) {
            addCriterion("total_supply =", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyNotEqualTo(String value) {
            addCriterion("total_supply <>", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyGreaterThan(String value) {
            addCriterion("total_supply >", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyGreaterThanOrEqualTo(String value) {
            addCriterion("total_supply >=", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyLessThan(String value) {
            addCriterion("total_supply <", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyLessThanOrEqualTo(String value) {
            addCriterion("total_supply <=", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyLike(String value) {
            addCriterion("total_supply like", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyNotLike(String value) {
            addCriterion("total_supply not like", value, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyIn(List<String> values) {
            addCriterion("total_supply in", values, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyNotIn(List<String> values) {
            addCriterion("total_supply not in", values, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyBetween(String value1, String value2) {
            addCriterion("total_supply between", value1, value2, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andTotalSupplyNotBetween(String value1, String value2) {
            addCriterion("total_supply not between", value1, value2, "totalSupply");
            return (Criteria) this;
        }

        public Criteria andDecimalsIsNull() {
            addCriterion("decimals is null");
            return (Criteria) this;
        }

        public Criteria andDecimalsIsNotNull() {
            addCriterion("decimals is not null");
            return (Criteria) this;
        }

        public Criteria andDecimalsEqualTo(Integer value) {
            addCriterion("decimals =", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsNotEqualTo(Integer value) {
            addCriterion("decimals <>", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsGreaterThan(Integer value) {
            addCriterion("decimals >", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsGreaterThanOrEqualTo(Integer value) {
            addCriterion("decimals >=", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsLessThan(Integer value) {
            addCriterion("decimals <", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsLessThanOrEqualTo(Integer value) {
            addCriterion("decimals <=", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsIn(List<Integer> values) {
            addCriterion("decimals in", values, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsNotIn(List<Integer> values) {
            addCriterion("decimals not in", values, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsBetween(Integer value1, Integer value2) {
            addCriterion("decimals between", value1, value2, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsNotBetween(Integer value1, Integer value2) {
            addCriterion("decimals not between", value1, value2, "decimals");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andActiveSortIsNull() {
            addCriterion("active_sort is null");
            return (Criteria) this;
        }

        public Criteria andActiveSortIsNotNull() {
            addCriterion("active_sort is not null");
            return (Criteria) this;
        }

        public Criteria andActiveSortEqualTo(Boolean value) {
            addCriterion("active_sort =", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortNotEqualTo(Boolean value) {
            addCriterion("active_sort <>", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortGreaterThan(Boolean value) {
            addCriterion("active_sort >", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortGreaterThanOrEqualTo(Boolean value) {
            addCriterion("active_sort >=", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortLessThan(Boolean value) {
            addCriterion("active_sort <", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortLessThanOrEqualTo(Boolean value) {
            addCriterion("active_sort <=", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortIn(List<Boolean> values) {
            addCriterion("active_sort in", values, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortNotIn(List<Boolean> values) {
            addCriterion("active_sort not in", values, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortBetween(Boolean value1, Boolean value2) {
            addCriterion("active_sort between", value1, value2, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortNotBetween(Boolean value1, Boolean value2) {
            addCriterion("active_sort not between", value1, value2, "activeSort");
            return (Criteria) this;
        }

        public Criteria andNameSortIsNull() {
            addCriterion("name_sort is null");
            return (Criteria) this;
        }

        public Criteria andNameSortIsNotNull() {
            addCriterion("name_sort is not null");
            return (Criteria) this;
        }

        public Criteria andNameSortEqualTo(Boolean value) {
            addCriterion("name_sort =", value, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortNotEqualTo(Boolean value) {
            addCriterion("name_sort <>", value, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortGreaterThan(Boolean value) {
            addCriterion("name_sort >", value, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortGreaterThanOrEqualTo(Boolean value) {
            addCriterion("name_sort >=", value, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortLessThan(Boolean value) {
            addCriterion("name_sort <", value, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortLessThanOrEqualTo(Boolean value) {
            addCriterion("name_sort <=", value, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortIn(List<Boolean> values) {
            addCriterion("name_sort in", values, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortNotIn(List<Boolean> values) {
            addCriterion("name_sort not in", values, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortBetween(Boolean value1, Boolean value2) {
            addCriterion("name_sort between", value1, value2, "nameSort");
            return (Criteria) this;
        }

        public Criteria andNameSortNotBetween(Boolean value1, Boolean value2) {
            addCriterion("name_sort not between", value1, value2, "nameSort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_CONTRACT
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}