package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TInternalTx extends TInternalTxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.parent_tx_hash
     *
     * @mbg.generated
     */
    private String parentTxHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.tx_index
     *
     * @mbg.generated
     */
    private Integer txIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.contract_addr
     *
     * @mbg.generated
     */
    private String contractAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.from_addr
     *
     * @mbg.generated
     */
    private String fromAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.to_addr
     *
     * @mbg.generated
     */
    private String toAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.parent_tx_hash
     *
     * @return the value of T_INTERNAL_TX.parent_tx_hash
     *
     * @mbg.generated
     */
    public String getParentTxHash() {
        return parentTxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.parent_tx_hash
     *
     * @param parentTxHash the value for T_INTERNAL_TX.parent_tx_hash
     *
     * @mbg.generated
     */
    public void setParentTxHash(String parentTxHash) {
        this.parentTxHash = parentTxHash == null ? null : parentTxHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.tx_index
     *
     * @return the value of T_INTERNAL_TX.tx_index
     *
     * @mbg.generated
     */
    public Integer getTxIndex() {
        return txIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.tx_index
     *
     * @param txIndex the value for T_INTERNAL_TX.tx_index
     *
     * @mbg.generated
     */
    public void setTxIndex(Integer txIndex) {
        this.txIndex = txIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.contract_addr
     *
     * @return the value of T_INTERNAL_TX.contract_addr
     *
     * @mbg.generated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.contract_addr
     *
     * @param contractAddr the value for T_INTERNAL_TX.contract_addr
     *
     * @mbg.generated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr == null ? null : contractAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.height
     *
     * @return the value of T_INTERNAL_TX.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.height
     *
     * @param height the value for T_INTERNAL_TX.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.create_date
     *
     * @return the value of T_INTERNAL_TX.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.create_date
     *
     * @param createDate the value for T_INTERNAL_TX.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.from_addr
     *
     * @return the value of T_INTERNAL_TX.from_addr
     *
     * @mbg.generated
     */
    public String getFromAddr() {
        return fromAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.from_addr
     *
     * @param fromAddr the value for T_INTERNAL_TX.from_addr
     *
     * @mbg.generated
     */
    public void setFromAddr(String fromAddr) {
        this.fromAddr = fromAddr == null ? null : fromAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.to_addr
     *
     * @return the value of T_INTERNAL_TX.to_addr
     *
     * @mbg.generated
     */
    public String getToAddr() {
        return toAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.to_addr
     *
     * @param toAddr the value for T_INTERNAL_TX.to_addr
     *
     * @mbg.generated
     */
    public void setToAddr(String toAddr) {
        this.toAddr = toAddr == null ? null : toAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX.amount
     *
     * @return the value of T_INTERNAL_TX.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX.amount
     *
     * @param amount the value for T_INTERNAL_TX.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }
}