package com.dfg.icon.core.dao.icon;

public class TInternalTxView extends TInternalTxViewKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX_VIEW.parent_tx_hash
     *
     * @mbg.generated
     */
    private String parentTxHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX_VIEW.tx_index
     *
     * @mbg.generated
     */
    private Integer txIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX_VIEW.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERNAL_TX_VIEW.address_type
     *
     * @mbg.generated
     */
    private Boolean addressType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX_VIEW.parent_tx_hash
     *
     * @return the value of T_INTERNAL_TX_VIEW.parent_tx_hash
     *
     * @mbg.generated
     */
    public String getParentTxHash() {
        return parentTxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX_VIEW.parent_tx_hash
     *
     * @param parentTxHash the value for T_INTERNAL_TX_VIEW.parent_tx_hash
     *
     * @mbg.generated
     */
    public void setParentTxHash(String parentTxHash) {
        this.parentTxHash = parentTxHash == null ? null : parentTxHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX_VIEW.tx_index
     *
     * @return the value of T_INTERNAL_TX_VIEW.tx_index
     *
     * @mbg.generated
     */
    public Integer getTxIndex() {
        return txIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX_VIEW.tx_index
     *
     * @param txIndex the value for T_INTERNAL_TX_VIEW.tx_index
     *
     * @mbg.generated
     */
    public void setTxIndex(Integer txIndex) {
        this.txIndex = txIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX_VIEW.address
     *
     * @return the value of T_INTERNAL_TX_VIEW.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX_VIEW.address
     *
     * @param address the value for T_INTERNAL_TX_VIEW.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERNAL_TX_VIEW.address_type
     *
     * @return the value of T_INTERNAL_TX_VIEW.address_type
     *
     * @mbg.generated
     */
    public Boolean getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERNAL_TX_VIEW.address_type
     *
     * @param addressType the value for T_INTERNAL_TX_VIEW.address_type
     *
     * @mbg.generated
     */
    public void setAddressType(Boolean addressType) {
        this.addressType = addressType;
    }
}