package com.dfg.icon.core.dao.icon;

public class TMainChart extends TMainChartKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_CHART.tx_count
     *
     * @mbg.generated
     */
    private Integer txCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_CHART.tx_count
     *
     * @return the value of T_MAIN_CHART.tx_count
     *
     * @mbg.generated
     */
    public Integer getTxCount() {
        return txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_CHART.tx_count
     *
     * @param txCount the value for T_MAIN_CHART.tx_count
     *
     * @mbg.generated
     */
    public void setTxCount(Integer txCount) {
        this.txCount = txCount;
    }
}