package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TMainBlock extends TMainBlockKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_BLOCK.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_BLOCK.tx_count
     *
     * @mbg.generated
     */
    private Integer txCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_BLOCK.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_BLOCK.hash
     *
     * @return the value of T_MAIN_BLOCK.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_BLOCK.hash
     *
     * @param hash the value for T_MAIN_BLOCK.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_BLOCK.tx_count
     *
     * @return the value of T_MAIN_BLOCK.tx_count
     *
     * @mbg.generated
     */
    public Integer getTxCount() {
        return txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_BLOCK.tx_count
     *
     * @param txCount the value for T_MAIN_BLOCK.tx_count
     *
     * @mbg.generated
     */
    public void setTxCount(Integer txCount) {
        this.txCount = txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_BLOCK.create_date
     *
     * @return the value of T_MAIN_BLOCK.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_BLOCK.create_date
     *
     * @param createDate the value for T_MAIN_BLOCK.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}