package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TMainTx extends TMainTxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_TX.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_TX.fee
     *
     * @mbg.generated
     */
    private String fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_TX.score_yn
     *
     * @mbg.generated
     */
    private String scoreYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_TX.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_TX.state
     *
     * @mbg.generated
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_TX.amount
     *
     * @return the value of T_MAIN_TX.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_TX.amount
     *
     * @param amount the value for T_MAIN_TX.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_TX.fee
     *
     * @return the value of T_MAIN_TX.fee
     *
     * @mbg.generated
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_TX.fee
     *
     * @param fee the value for T_MAIN_TX.fee
     *
     * @mbg.generated
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_TX.score_yn
     *
     * @return the value of T_MAIN_TX.score_yn
     *
     * @mbg.generated
     */
    public String getScoreYn() {
        return scoreYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_TX.score_yn
     *
     * @param scoreYn the value for T_MAIN_TX.score_yn
     *
     * @mbg.generated
     */
    public void setScoreYn(String scoreYn) {
        this.scoreYn = scoreYn == null ? null : scoreYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_TX.create_date
     *
     * @return the value of T_MAIN_TX.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_TX.create_date
     *
     * @param createDate the value for T_MAIN_TX.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_TX.state
     *
     * @return the value of T_MAIN_TX.state
     *
     * @mbg.generated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_TX.state
     *
     * @param state the value for T_MAIN_TX.state
     *
     * @mbg.generated
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}