package com.dfg.icon.core.dao.icon;

public class TMainInfo extends TMainInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_INFO.transaction_count
     *
     * @mbg.generated
     */
    private Integer transactionCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_INFO.transaction_count
     *
     * @return the value of T_MAIN_INFO.transaction_count
     *
     * @mbg.generated
     */
    public Integer getTransactionCount() {
        return transactionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_INFO.transaction_count
     *
     * @param transactionCount the value for T_MAIN_INFO.transaction_count
     *
     * @mbg.generated
     */
    public void setTransactionCount(Integer transactionCount) {
        this.transactionCount = transactionCount;
    }
}