package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TSchedulerFlag extends TSchedulerFlagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCHEDULER_FLAG.active_yn
     *
     * @mbg.generated
     */
    private String activeYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCHEDULER_FLAG.active_server
     *
     * @mbg.generated
     */
    private String activeServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCHEDULER_FLAG.start_position
     *
     * @mbg.generated
     */
    private String startPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCHEDULER_FLAG.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCHEDULER_FLAG.active_yn
     *
     * @return the value of T_SCHEDULER_FLAG.active_yn
     *
     * @mbg.generated
     */
    public String getActiveYn() {
        return activeYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCHEDULER_FLAG.active_yn
     *
     * @param activeYn the value for T_SCHEDULER_FLAG.active_yn
     *
     * @mbg.generated
     */
    public void setActiveYn(String activeYn) {
        this.activeYn = activeYn == null ? null : activeYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCHEDULER_FLAG.active_server
     *
     * @return the value of T_SCHEDULER_FLAG.active_server
     *
     * @mbg.generated
     */
    public String getActiveServer() {
        return activeServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCHEDULER_FLAG.active_server
     *
     * @param activeServer the value for T_SCHEDULER_FLAG.active_server
     *
     * @mbg.generated
     */
    public void setActiveServer(String activeServer) {
        this.activeServer = activeServer == null ? null : activeServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCHEDULER_FLAG.start_position
     *
     * @return the value of T_SCHEDULER_FLAG.start_position
     *
     * @mbg.generated
     */
    public String getStartPosition() {
        return startPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCHEDULER_FLAG.start_position
     *
     * @param startPosition the value for T_SCHEDULER_FLAG.start_position
     *
     * @mbg.generated
     */
    public void setStartPosition(String startPosition) {
        this.startPosition = startPosition == null ? null : startPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCHEDULER_FLAG.update_date
     *
     * @return the value of T_SCHEDULER_FLAG.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCHEDULER_FLAG.update_date
     *
     * @param updateDate the value for T_SCHEDULER_FLAG.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}