package com.dfg.icon.core.dao.icon;

public class TSchedulerFlagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCHEDULER_FLAG.schedule_name
     *
     * @mbg.generated
     */
    private String scheduleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCHEDULER_FLAG.schedule_name
     *
     * @return the value of T_SCHEDULER_FLAG.schedule_name
     *
     * @mbg.generated
     */
    public String getScheduleName() {
        return scheduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCHEDULER_FLAG.schedule_name
     *
     * @param scheduleName the value for T_SCHEDULER_FLAG.schedule_name
     *
     * @mbg.generated
     */
    public void setScheduleName(String scheduleName) {
        this.scheduleName = scheduleName == null ? null : scheduleName.trim();
    }
}