package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TTokenTx extends TTokenTxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.contract_addr
     *
     * @mbg.generated
     */
    private String contractAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.tx_index
     *
     * @mbg.generated
     */
    private Integer txIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.block_height
     *
     * @mbg.generated
     */
    private Integer blockHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.age
     *
     * @mbg.generated
     */
    private Date age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.from_addr
     *
     * @mbg.generated
     */
    private String fromAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.to_addr
     *
     * @mbg.generated
     */
    private String toAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.quantity
     *
     * @mbg.generated
     */
    private String quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.irc_version
     *
     * @mbg.generated
     */
    private String ircVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TOKEN_TX.fee
     *
     * @mbg.generated
     */
    private String fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.contract_addr
     *
     * @return the value of T_TOKEN_TX.contract_addr
     *
     * @mbg.generated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.contract_addr
     *
     * @param contractAddr the value for T_TOKEN_TX.contract_addr
     *
     * @mbg.generated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr == null ? null : contractAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.tx_hash
     *
     * @return the value of T_TOKEN_TX.tx_hash
     *
     * @mbg.generated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.tx_hash
     *
     * @param txHash the value for T_TOKEN_TX.tx_hash
     *
     * @mbg.generated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.tx_index
     *
     * @return the value of T_TOKEN_TX.tx_index
     *
     * @mbg.generated
     */
    public Integer getTxIndex() {
        return txIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.tx_index
     *
     * @param txIndex the value for T_TOKEN_TX.tx_index
     *
     * @mbg.generated
     */
    public void setTxIndex(Integer txIndex) {
        this.txIndex = txIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.block_height
     *
     * @return the value of T_TOKEN_TX.block_height
     *
     * @mbg.generated
     */
    public Integer getBlockHeight() {
        return blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.block_height
     *
     * @param blockHeight the value for T_TOKEN_TX.block_height
     *
     * @mbg.generated
     */
    public void setBlockHeight(Integer blockHeight) {
        this.blockHeight = blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.age
     *
     * @return the value of T_TOKEN_TX.age
     *
     * @mbg.generated
     */
    public Date getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.age
     *
     * @param age the value for T_TOKEN_TX.age
     *
     * @mbg.generated
     */
    public void setAge(Date age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.from_addr
     *
     * @return the value of T_TOKEN_TX.from_addr
     *
     * @mbg.generated
     */
    public String getFromAddr() {
        return fromAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.from_addr
     *
     * @param fromAddr the value for T_TOKEN_TX.from_addr
     *
     * @mbg.generated
     */
    public void setFromAddr(String fromAddr) {
        this.fromAddr = fromAddr == null ? null : fromAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.to_addr
     *
     * @return the value of T_TOKEN_TX.to_addr
     *
     * @mbg.generated
     */
    public String getToAddr() {
        return toAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.to_addr
     *
     * @param toAddr the value for T_TOKEN_TX.to_addr
     *
     * @mbg.generated
     */
    public void setToAddr(String toAddr) {
        this.toAddr = toAddr == null ? null : toAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.quantity
     *
     * @return the value of T_TOKEN_TX.quantity
     *
     * @mbg.generated
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.quantity
     *
     * @param quantity the value for T_TOKEN_TX.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity == null ? null : quantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.irc_version
     *
     * @return the value of T_TOKEN_TX.irc_version
     *
     * @mbg.generated
     */
    public String getIrcVersion() {
        return ircVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.irc_version
     *
     * @param ircVersion the value for T_TOKEN_TX.irc_version
     *
     * @mbg.generated
     */
    public void setIrcVersion(String ircVersion) {
        this.ircVersion = ircVersion == null ? null : ircVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TOKEN_TX.fee
     *
     * @return the value of T_TOKEN_TX.fee
     *
     * @mbg.generated
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TOKEN_TX.fee
     *
     * @param fee the value for T_TOKEN_TX.fee
     *
     * @mbg.generated
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }
}