package com.dfg.icon.core.dao.icon;

public class TTransactionView extends TTransactionViewKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_VIEW.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_VIEW.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_VIEW.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_VIEW.address_type
     *
     * @mbg.generated
     */
    private Byte addressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_VIEW.tx_type
     *
     * @mbg.generated
     */
    private Byte txType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_VIEW.tx_hash
     *
     * @return the value of T_TRANSACTION_VIEW.tx_hash
     *
     * @mbg.generated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_VIEW.tx_hash
     *
     * @param txHash the value for T_TRANSACTION_VIEW.tx_hash
     *
     * @mbg.generated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_VIEW.height
     *
     * @return the value of T_TRANSACTION_VIEW.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_VIEW.height
     *
     * @param height the value for T_TRANSACTION_VIEW.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_VIEW.address
     *
     * @return the value of T_TRANSACTION_VIEW.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_VIEW.address
     *
     * @param address the value for T_TRANSACTION_VIEW.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_VIEW.address_type
     *
     * @return the value of T_TRANSACTION_VIEW.address_type
     *
     * @mbg.generated
     */
    public Byte getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_VIEW.address_type
     *
     * @param addressType the value for T_TRANSACTION_VIEW.address_type
     *
     * @mbg.generated
     */
    public void setAddressType(Byte addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_VIEW.tx_type
     *
     * @return the value of T_TRANSACTION_VIEW.tx_type
     *
     * @mbg.generated
     */
    public Byte getTxType() {
        return txType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_VIEW.tx_type
     *
     * @param txType the value for T_TRANSACTION_VIEW.tx_type
     *
     * @mbg.generated
     */
    public void setTxType(Byte txType) {
        this.txType = txType;
    }
}