package com.dfg.icon.core.dao.icon;

public class TTransactionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.tx_hash
     *
     * @return the value of T_TRANSACTION.tx_hash
     *
     * @mbg.generated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.tx_hash
     *
     * @param txHash the value for T_TRANSACTION.tx_hash
     *
     * @mbg.generated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }
}