package com.dfg.icon.core.dao.icon;

public class TTransactionTotalWithBLOBs extends TTransactionTotal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_TOTAL.error_msg
     *
     * @mbg.generated
     */
    private String errorMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_TOTAL.error_msg
     *
     * @return the value of T_TRANSACTION_TOTAL.error_msg
     *
     * @mbg.generated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_TOTAL.error_msg
     *
     * @param errorMsg the value for T_TRANSACTION_TOTAL.error_msg
     *
     * @mbg.generated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }
}