package com.dfg.icon.core.dao.icon;

import java.util.Date;

public class TTransaction extends TTransactionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.from_addr
     *
     * @mbg.generated
     */
    private String fromAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.to_addr
     *
     * @mbg.generated
     */
    private String toAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.fee
     *
     * @mbg.generated
     */
    private String fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.state
     *
     * @mbg.generated
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.tx_type
     *
     * @mbg.generated
     */
    private Byte txType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION.contract_addr
     *
     * @mbg.generated
     */
    private String contractAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.height
     *
     * @return the value of T_TRANSACTION.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.height
     *
     * @param height the value for T_TRANSACTION.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.create_date
     *
     * @return the value of T_TRANSACTION.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.create_date
     *
     * @param createDate the value for T_TRANSACTION.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.from_addr
     *
     * @return the value of T_TRANSACTION.from_addr
     *
     * @mbg.generated
     */
    public String getFromAddr() {
        return fromAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.from_addr
     *
     * @param fromAddr the value for T_TRANSACTION.from_addr
     *
     * @mbg.generated
     */
    public void setFromAddr(String fromAddr) {
        this.fromAddr = fromAddr == null ? null : fromAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.to_addr
     *
     * @return the value of T_TRANSACTION.to_addr
     *
     * @mbg.generated
     */
    public String getToAddr() {
        return toAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.to_addr
     *
     * @param toAddr the value for T_TRANSACTION.to_addr
     *
     * @mbg.generated
     */
    public void setToAddr(String toAddr) {
        this.toAddr = toAddr == null ? null : toAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.fee
     *
     * @return the value of T_TRANSACTION.fee
     *
     * @mbg.generated
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.fee
     *
     * @param fee the value for T_TRANSACTION.fee
     *
     * @mbg.generated
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.amount
     *
     * @return the value of T_TRANSACTION.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.amount
     *
     * @param amount the value for T_TRANSACTION.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.state
     *
     * @return the value of T_TRANSACTION.state
     *
     * @mbg.generated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.state
     *
     * @param state the value for T_TRANSACTION.state
     *
     * @mbg.generated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.tx_type
     *
     * @return the value of T_TRANSACTION.tx_type
     *
     * @mbg.generated
     */
    public Byte getTxType() {
        return txType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.tx_type
     *
     * @param txType the value for T_TRANSACTION.tx_type
     *
     * @mbg.generated
     */
    public void setTxType(Byte txType) {
        this.txType = txType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION.contract_addr
     *
     * @return the value of T_TRANSACTION.contract_addr
     *
     * @mbg.generated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION.contract_addr
     *
     * @param contractAddr the value for T_TRANSACTION.contract_addr
     *
     * @mbg.generated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr == null ? null : contractAddr.trim();
    }
}