package com.dfg.icon.core.dao.icon;

public class TTxData extends TTxDataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TX_DATA.is_safe
     *
     * @mbg.generated
     */
    private Boolean isSafe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TX_DATA.is_safe
     *
     * @return the value of T_TX_DATA.is_safe
     *
     * @mbg.generated
     */
    public Boolean getIsSafe() {
        return isSafe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TX_DATA.is_safe
     *
     * @param isSafe the value for T_TX_DATA.is_safe
     *
     * @mbg.generated
     */
    public void setIsSafe(Boolean isSafe) {
        this.isSafe = isSafe;
    }
}