package com.dfg.icon.core.dao.icon;

public class TTxResultLogKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TX_RESULT_LOG.e_index
     *
     * @mbg.generated
     */
    private Integer eIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TX_RESULT_LOG.e_index
     *
     * @return the value of T_TX_RESULT_LOG.e_index
     *
     * @mbg.generated
     */
    public Integer geteIndex() {
        return eIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TX_RESULT_LOG.e_index
     *
     * @param eIndex the value for T_TX_RESULT_LOG.e_index
     *
     * @mbg.generated
     */
    public void seteIndex(Integer eIndex) {
        this.eIndex = eIndex;
    }
}