package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TAddress;
import com.dfg.icon.core.dao.icon.TAddressExample;
import com.dfg.icon.core.dao.icon.TAddressKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    long countByExample(TAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int deleteByExample(TAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int insert(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int insertSelective(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    List<TAddress> selectByExampleWithRowbounds(TAddressExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    List<TAddress> selectByExample(TAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    TAddress selectByPrimaryKey(TAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAddress record, @Param("example") TAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAddress record, @Param("example") TAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddress record);
}