package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TAddressHistory;
import com.dfg.icon.core.dao.icon.TAddressHistoryExample;
import com.dfg.icon.core.dao.icon.TAddressHistoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAddressHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    long countByExample(TAddressHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int deleteByExample(TAddressHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAddressHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int insert(TAddressHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int insertSelective(TAddressHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    List<TAddressHistory> selectByExampleWithRowbounds(TAddressHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    List<TAddressHistory> selectByExample(TAddressHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    TAddressHistory selectByPrimaryKey(TAddressHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAddressHistory record, @Param("example") TAddressHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAddressHistory record, @Param("example") TAddressHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddressHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_HISTORY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddressHistory record);
}