package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TAddressPush;
import com.dfg.icon.core.dao.icon.TAddressPushExample;
import com.dfg.icon.core.dao.icon.TAddressPushKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAddressPushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    long countByExample(TAddressPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int deleteByExample(TAddressPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAddressPushKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int insert(TAddressPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int insertSelective(TAddressPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    List<TAddressPush> selectByExampleWithRowbounds(TAddressPushExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    List<TAddressPush> selectByExample(TAddressPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    TAddressPush selectByPrimaryKey(TAddressPushKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAddressPush record, @Param("example") TAddressPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAddressPush record, @Param("example") TAddressPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddressPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PUSH
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddressPush record);
}