package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TAddressPrep;
import com.dfg.icon.core.dao.icon.TAddressPrepExample;
import com.dfg.icon.core.dao.icon.TAddressPrepKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAddressPrepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    long countByExample(TAddressPrepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int deleteByExample(TAddressPrepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAddressPrepKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int insert(TAddressPrep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int insertSelective(TAddressPrep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    List<TAddressPrep> selectByExampleWithRowbounds(TAddressPrepExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    List<TAddressPrep> selectByExample(TAddressPrepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    TAddressPrep selectByPrimaryKey(TAddressPrepKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAddressPrep record, @Param("example") TAddressPrepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAddressPrep record, @Param("example") TAddressPrepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddressPrep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_PREP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddressPrep record);
}