package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TAddressTotal;
import com.dfg.icon.core.dao.icon.TAddressTotalExample;
import com.dfg.icon.core.dao.icon.TAddressTotalKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAddressTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    long countByExample(TAddressTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int deleteByExample(TAddressTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAddressTotalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int insert(TAddressTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int insertSelective(TAddressTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    List<TAddressTotal> selectByExampleWithRowbounds(TAddressTotalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    List<TAddressTotal> selectByExample(TAddressTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    TAddressTotal selectByPrimaryKey(TAddressTotalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAddressTotal record, @Param("example") TAddressTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAddressTotal record, @Param("example") TAddressTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddressTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADDRESS_TOTAL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddressTotal record);
}