package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TBlockTotal;
import com.dfg.icon.core.dao.icon.TBlockTotalExample;
import com.dfg.icon.core.dao.icon.TBlockTotalKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TBlockTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    long countByExample(TBlockTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int deleteByExample(TBlockTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TBlockTotalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int insert(TBlockTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int insertSelective(TBlockTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    List<TBlockTotal> selectByExampleWithRowbounds(TBlockTotalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    List<TBlockTotal> selectByExample(TBlockTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    TBlockTotal selectByPrimaryKey(TBlockTotalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBlockTotal record, @Param("example") TBlockTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBlockTotal record, @Param("example") TBlockTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBlockTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOCK_TOTAL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBlockTotal record);
}