package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TBtpNetwork;
import com.dfg.icon.core.dao.icon.TBtpNetworkExample;
import com.dfg.icon.core.dao.icon.TBtpNetworkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TBtpNetworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    long countByExample(TBtpNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int deleteByExample(TBtpNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TBtpNetworkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int insert(TBtpNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int insertSelective(TBtpNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    List<TBtpNetwork> selectByExampleWithRowbounds(TBtpNetworkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    List<TBtpNetwork> selectByExample(TBtpNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    TBtpNetwork selectByPrimaryKey(TBtpNetworkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBtpNetwork record, @Param("example") TBtpNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBtpNetwork record, @Param("example") TBtpNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBtpNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BTP_NETWORK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBtpNetwork record);
}