package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TChainInfo;
import com.dfg.icon.core.dao.icon.TChainInfoExample;
import com.dfg.icon.core.dao.icon.TChainInfoKey;
import java.util.List;

import com.dfg.icon.web.v3.dto.ChainInfo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TChainInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    long countByExample(TChainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int deleteByExample(TChainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TChainInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int insert(TChainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int insertSelective(TChainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    List<TChainInfo> selectByExampleWithRowbounds(TChainInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    List<TChainInfo> selectByExample(TChainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    TChainInfo selectByPrimaryKey(TChainInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TChainInfo record, @Param("example") TChainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TChainInfo record, @Param("example") TChainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TChainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CHAIN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TChainInfo record);

    int chainInfoByName(@Param("chainName") String chainName);

    List<ChainInfo> selectAll();

}