package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TContract;
import com.dfg.icon.core.dao.icon.TContractExample;
import com.dfg.icon.core.dao.icon.TContractKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    long countByExample(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int deleteByExample(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TContractKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int insert(TContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int insertSelective(TContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    List<TContract> selectByExampleWithRowbounds(TContractExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    List<TContract> selectByExample(TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    TContract selectByPrimaryKey(TContractKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TContract record, @Param("example") TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TContract record, @Param("example") TContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CONTRACT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TContract record);
}