package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TFeeDetails;
import com.dfg.icon.core.dao.icon.TFeeDetailsExample;
import com.dfg.icon.core.dao.icon.TFeeDetailsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TFeeDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    long countByExample(TFeeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int deleteByExample(TFeeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TFeeDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int insert(TFeeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int insertSelective(TFeeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    List<TFeeDetails> selectByExampleWithRowbounds(TFeeDetailsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    List<TFeeDetails> selectByExample(TFeeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    TFeeDetails selectByPrimaryKey(TFeeDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFeeDetails record, @Param("example") TFeeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFeeDetails record, @Param("example") TFeeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFeeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FEE_DETAILS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFeeDetails record);
}