package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TInternalTx;
import com.dfg.icon.core.dao.icon.TInternalTxExample;
import com.dfg.icon.core.dao.icon.TInternalTxKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TInternalTxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    long countByExample(TInternalTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int deleteByExample(TInternalTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TInternalTxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int insert(TInternalTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int insertSelective(TInternalTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    List<TInternalTx> selectByExampleWithRowbounds(TInternalTxExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    List<TInternalTx> selectByExample(TInternalTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    TInternalTx selectByPrimaryKey(TInternalTxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInternalTx record, @Param("example") TInternalTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInternalTx record, @Param("example") TInternalTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInternalTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInternalTx record);
}