package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TInternalTxView;
import com.dfg.icon.core.dao.icon.TInternalTxViewExample;
import com.dfg.icon.core.dao.icon.TInternalTxViewKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TInternalTxViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    long countByExample(TInternalTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int deleteByExample(TInternalTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TInternalTxViewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int insert(TInternalTxView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int insertSelective(TInternalTxView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    List<TInternalTxView> selectByExampleWithRowbounds(TInternalTxViewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    List<TInternalTxView> selectByExample(TInternalTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    TInternalTxView selectByPrimaryKey(TInternalTxViewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInternalTxView record, @Param("example") TInternalTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInternalTxView record, @Param("example") TInternalTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInternalTxView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INTERNAL_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInternalTxView record);
}