package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TMainTx;
import com.dfg.icon.core.dao.icon.TMainTxExample;
import com.dfg.icon.core.dao.icon.TMainTxKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TMainTxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    long countByExample(TMainTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int deleteByExample(TMainTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TMainTxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int insert(TMainTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int insertSelective(TMainTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    List<TMainTx> selectByExampleWithRowbounds(TMainTxExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    List<TMainTx> selectByExample(TMainTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    TMainTx selectByPrimaryKey(TMainTxKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMainTx record, @Param("example") TMainTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMainTx record, @Param("example") TMainTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMainTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_TX
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMainTx record);
}