package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TMainBlock;
import com.dfg.icon.core.dao.icon.TMainBlockExample;
import com.dfg.icon.core.dao.icon.TMainBlockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TMainBlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    long countByExample(TMainBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int deleteByExample(TMainBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TMainBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int insert(TMainBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int insertSelective(TMainBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    List<TMainBlock> selectByExampleWithRowbounds(TMainBlockExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    List<TMainBlock> selectByExample(TMainBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    TMainBlock selectByPrimaryKey(TMainBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMainBlock record, @Param("example") TMainBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMainBlock record, @Param("example") TMainBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMainBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_BLOCK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMainBlock record);
}