package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TMainInfo;
import com.dfg.icon.core.dao.icon.TMainInfoExample;
import com.dfg.icon.core.dao.icon.TMainInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TMainInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    long countByExample(TMainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int deleteByExample(TMainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TMainInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int insert(TMainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int insertSelective(TMainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    List<TMainInfo> selectByExampleWithRowbounds(TMainInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    List<TMainInfo> selectByExample(TMainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    TMainInfo selectByPrimaryKey(TMainInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMainInfo record, @Param("example") TMainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMainInfo record, @Param("example") TMainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMainInfo record);
}