package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TMainChart;
import com.dfg.icon.core.dao.icon.TMainChartExample;
import com.dfg.icon.core.dao.icon.TMainChartKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TMainChartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    long countByExample(TMainChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int deleteByExample(TMainChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TMainChartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int insert(TMainChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int insertSelective(TMainChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    List<TMainChart> selectByExampleWithRowbounds(TMainChartExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    List<TMainChart> selectByExample(TMainChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    TMainChart selectByPrimaryKey(TMainChartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMainChart record, @Param("example") TMainChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMainChart record, @Param("example") TMainChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMainChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_CHART
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMainChart record);
}