package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TTokenTxView;
import com.dfg.icon.core.dao.icon.TTokenTxViewExample;
import com.dfg.icon.core.dao.icon.TTokenTxViewKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TTokenTxViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    long countByExample(TTokenTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int deleteByExample(TTokenTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TTokenTxViewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int insert(TTokenTxView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int insertSelective(TTokenTxView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    List<TTokenTxView> selectByExampleWithRowbounds(TTokenTxViewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    List<TTokenTxView> selectByExample(TTokenTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    TTokenTxView selectByPrimaryKey(TTokenTxViewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTokenTxView record, @Param("example") TTokenTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTokenTxView record, @Param("example") TTokenTxViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTokenTxView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TOKEN_TX_VIEW
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTokenTxView record);
}