package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TTxData;
import com.dfg.icon.core.dao.icon.TTxDataExample;
import com.dfg.icon.core.dao.icon.TTxDataKey;
import com.dfg.icon.core.dao.icon.TTxDataWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TTxDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    long countByExample(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int deleteByExample(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TTxDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int insert(TTxDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int insertSelective(TTxDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    List<TTxDataWithBLOBs> selectByExampleWithBLOBsWithRowbounds(TTxDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    List<TTxDataWithBLOBs> selectByExampleWithBLOBs(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    List<TTxData> selectByExampleWithRowbounds(TTxDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    List<TTxData> selectByExample(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    TTxDataWithBLOBs selectByPrimaryKey(TTxDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTxDataWithBLOBs record, @Param("example") TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TTxDataWithBLOBs record, @Param("example") TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTxData record, @Param("example") TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTxDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TTxDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_DATA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTxData record);
}