package com.dfg.icon.core.mappers.icon;

import com.dfg.icon.core.dao.icon.TTxResultLog;
import com.dfg.icon.core.dao.icon.TTxResultLogExample;
import com.dfg.icon.core.dao.icon.TTxResultLogKey;
import com.dfg.icon.core.dao.icon.TTxResultLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TTxResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    long countByExample(TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int deleteByExample(TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TTxResultLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int insert(TTxResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int insertSelective(TTxResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    List<TTxResultLogWithBLOBs> selectByExampleWithBLOBsWithRowbounds(TTxResultLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    List<TTxResultLogWithBLOBs> selectByExampleWithBLOBs(TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    List<TTxResultLog> selectByExampleWithRowbounds(TTxResultLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    List<TTxResultLog> selectByExample(TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    TTxResultLogWithBLOBs selectByPrimaryKey(TTxResultLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTxResultLogWithBLOBs record, @Param("example") TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TTxResultLogWithBLOBs record, @Param("example") TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTxResultLog record, @Param("example") TTxResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTxResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TTxResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TX_RESULT_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTxResultLog record);
}